services:
  wallet-service:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@dhwaniastro-postgres:5432/astro
      RABBITMQ_URL: amqp://guest:guest@dhwaniastro-rabbitmq:5672
    ports:
      - "8003:8003"
    networks:
      - dhwaniastro-net  # attach to external network so it can reach Postgres & RabbitMQ

networks:
  dhwaniastro-net:
    external: true